console.log("Hello World");
var x : number = 100;
console.log("Integer Value " + x);
var y : number = 123.567;
console.log("Float Value " + y);
var str : string = "TypeScript Programming";
console.log("String Value " + str);
var s : boolean = true;
console.log("Boolean Value " + s);
var n : any = "Angular Sessions";
console.log("Any Data Type Value " + n);
var n1 : any = 10.98;
console.log("Any Data Type Value " + n1);